modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "Apache 2.0"

[[mods]]
modId = "iinpulib"
version = "${version}"
displayName = "iinpulib"
authors = "norivensuu"
description = '''
Uhhh dis just a silly lib. Don't mind it :>
'''
#logoFile = ""

[[dependencies.iinpulib]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iinpulib]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iinpulib]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "iinpulib.mixins.json"
